name: Deploy to GKE

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      IMAGE: us-west1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/python-repo/python-app
      CLUSTER: ${{ secrets.CLUSTER }}
      REGION: ${{ secrets.REGION }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Debug Image name
      run: |
        echo ${{ vars.CLUSTER }}
        echo ${{ vars.PROJECT_ID }}
        echo ${{ vars.REGION }}
