name: Deploy to GKE

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ variables.PROJECT_ID }}
      IMAGE: gcr.io/${{ variables.PROJECT_ID }}/python-app
      CLUSTER: ${{ variables.CLUSTER }}
      REGION: ${{ variables.REGION }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ variables.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Debug Image name
      run: |
        echo "PROJECT_ID=$PROJECT_ID"
        echo "IMAGE=$IMAGE"

    - name: Auth Docker to GCR
      run: gcloud auth configure-docker --quiet

    - name: Build Docker image
      run: docker build -t $IMAGE:latest .

    - name: Push Docker image
      run: docker push $IMAGE:latest
