name: Deploy to GKE

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    container:
      image: google/cloud-sdk:latest

    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      IMAGE: us-west1-docker.pkg.dev/${{ vars.PROJECT_ID }}/python-repo/python-app
      CLUSTER: ${{ vars.CLUSTER }}
      REGION: ${{ vars.REGION }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-west1-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        docker build -t $IMAGE:$GITHUB_SHA .
        docker push $IMAGE:$GITHUB_SHA

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $CLUSTER --region $REGION --project $PROJECT_ID

    - name: Deploy manifest to GKE
      run: |
        kubectl apply -f app/k8s/deployment.yaml
        kubectl apply -f app/k8s/service.yaml

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/python-app python-app=$IMAGE:$GITHUB_SHA --namespace=default
