name: Deploy to GKE

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      IMAGE: us-west1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/python-images/python-app
      CLUSTER: ${{ secrets.CLUSTER }}
      REGION: ${{ secrets.REGION }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Debug Image name
      run: |
        echo "PROJECT_ID=$PROJECT_ID"
        echo "IMAGE=$IMAGE"

    - name: Auth Docker to Artifact Registry
      run: gcloud auth configure-docker us-west1-docker.pkg.dev

    - name: Build Docker image
      run: docker build -t $IMAGE:latest .

    - name: Push Docker image
      run: docker push $IMAGE:latest
